config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users do
	collection do
	  post :import
	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  
  def self.import(file)
		begin
			CSV.foreach(file.path, headers: true) do |row|
			  User.create! row.to_hash
			end
		rescue Exception => e
				return false
		end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def import
    if User.import(params[:file])
      flash[:notice] = 'Data uploaded successfully'
    else
      flash[:error] = 'File not found'
    end
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestVisit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.slim
h4= "Import CSV"

div class="center-div form-inline"
	= form_tag import_users_path, multipart: true do
	  = file_field_tag :file
	  = submit_tag "Import", class: "btn btn-primary"
br/

div class="center-div"  
	table class="table table-striped" id = "product_lists"
	  thead
	    tr
	      th Name
	      th Date
	      th Number
	      th Description
	  tbody
	    - @users.each do |user|
	      tr
	        td= user.name
	        td= user.date
	        td= user.number
	        td= user.description

app/views/welcome/index.html.slim
h1 Visit.org Sample Project
p
  | Please complete the items on the checklist.
  
  span<> = link_to 'This is the CSV to use.', 'test.csv'

h3 Checklist
ol
  li Create model to store CSV data
  li Upload CSV via a form
  li Save CSV records to database
  li Display success/error message
  li Display users in table